//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 dacview.RC 使用
//
#define IDR_MAINFRAME                   2
#define IDR_VIEWTYPE                    3
#define IDB_STYLES                      3
#define IDR_SHOWTYPE                    4
#define IDR_STRATEGYTYPE                5
#define IDS_STRATEGY_FILE_VERSION       6
#define IDS_VIEW_FILE_VERSION           7
#define IDR_MESSAGETYPE                 8
#define IDD_ABOUTBOX                    100
#define DLGOPEN_EDIT                    101
#define DLGOPEN_FILE_LISTBOX            102
#define IDD_SETPROPERTY                 103
#define IDD_OBJECT_VIRTUAL_RECT         103
#define DLGOPEN_DIR_LISTBOX             103
#define IDC_ObjectName                  104
#define IDD_DYNAMIC_LINK                104
#define DLGOPEN_PATH                    104
#define IDC_BUFFER_LENGTH               105
#define IDB_OBJECT                      106
#define IDC_BUTTONFORECOLOR             106
#define ID_MOUSE_POSITION               106
#define IDC_DYNAMIC_LINK                106
#define DLGOPEN_FOLDOUT                 106
#define IDC_BUTTONBACKCOLOR             107
#define ID_RECT_POSITION                107
#define IDD_CHOICE_LINK                 107
#define DLGOPEN_BIG                     107
#define IDD_UNIT_QUADRATIC              108
#define IDC_ANGLE                       108
#define IDC_BUTTONNORMAL                108
#define DLGOPEN_SMALL                   108
#define IDC_BUTTON_BAR_COLOR            108
#define IDD_CHOICE_LINK2                108
#define IDC_LINK_METHOD                 109
#define IDD_UNIT_SINE                   109
#define IDC_BUTTONWARN                  109
#define IDC_TAG_NAME                    110
#define ID_SYSTEM_TIME                  110
#define IDC_BUTTONERROR                 110
#define IDC_COMMENT                     111
#define IDD_UNIT_MULTIPLE               111
#define ID_SYSTEM_TIME_ALLOCATE         111
#define IDC_BUTTONNODDLE                111
#define IDD_UNIT_ADD                    112
#define IDS_DACVIEW_STRATEGY_COMPILE    112
#define IDD_UNIT_AND                    113
#define ID_REALTIME_TIME_ALLOCATE       113
#define IDD_UNIT_OR                     114
#define IDC_VARIABLE_TYPE               115
#define IDD_UNIT_INV                    115
#define IDC_LINK_NAME                   116
#define IDD_UNIT_XOR                    116
#define IDD_UNIT_DELAY                  117
#define IDC_VARIABLE_GROUP              118
#define IDC_VARIABLE_PARAMETER          118
#define IDD_UNIT_FFLP                   118
#define IDC_BUTTON_NEW                  119
#define IDD_UNIT_HPBG                   119
#define IDC_BUTTON_PREV                 120
#define IDD_UNIT_PULSE                  120
#define IDD_UNIT_TTB                    121
#define IDD_UNIT_SWCH                   122
#define IDD_UNIT_HSEL                   123
#define IDD_UNIT_MSEL                   124
#define IDD_UNIT_LSEL                   125
#define IDD_UNIT_QFLT                   126
#define IDC_ALARM                       127
#define IDD_DIALOG_DELETE_DYNLINK       127
#define IDC_DATAIL                      128
#define IDD_DIALOG_DELETE_ODYNLINK      128
#define IDD_SET_GRAPH_PROPERTY          129
#define IDD_OBJECT_GRAPH                129
#define IDD_SET_GAUGE_PROPERTY          130
#define IDD_OBJECT_GAUGE                130
#define IDD_UNIT_PID                    131
#define IDD_UNIT_TOT                    132
#define IDD_UNIT_IPOP                   133
#define IDC_BUTTON_NEXT                 134
#define IDD_UNIT_DIVIDE                 134
#define IDD_UNIT_DELAY_TIME             135
#define IDD_UNIT_TPO                    136
#define IDD_UNIT_BASE_DLG               137
#define IDD_OBJECT_SLIDER               138
#define IDC_COMBO_CHOICE_PARAMETER      139
#define IDD_OBJECT_KNOB                 139
#define IDD_OBJECT_BUTTON               140
#define IDD_OBJECT_METER                141
#define IDC_BUTTON_DELETE               142
#define IDD_OBJECT_FILLBAR              142
#define IDD_OBJECT_COMPOUND             143
#define IDC_BUTTON_UNDELETE             143
#define IDD_XDLGOPENBOX                 145
#define IDD_DLGOPENBOX                  146
#define IDD_OBJECT_TEXT                 147
#define IDD_OBJECT_ROUND_RECT           148
#define IDC_EDIT_NAME                   149
#define IDD_OBJECT_LINE                 149
#define IDD_VIEW_MESSAGE                150
#define IDC_EDIT_K2                     151
#define IDD_DIALOG_TASK_VIEW            151
#define IDC_EDIT_K1                     152
#define IDD_OBJECT_SYMBOL               152
#define IDC_EDIT_K0                     153
#define IDD_OBJECT_NUMBER_INPUT         153
#define IDC_EDIT_SCANRATE               154
#define IDB_COMPANY_NAME                154
#define IDD_SYSTEM_OPTION               154
#define IDC_EDIT_HIRANGE                155
#define IDC_EDIT_STR_ON                 155
#define IDC_EDIT_BITMAP                 155
#define IDC_BITMAP                      155
#define IDC_EDIT_TITLE                  155
#define IDC_EDIT_SHOW_NAME              155
#define IDC_EDIT_LORANGE                156
#define IDC_EDIT_STR_OFF                156
#define IDB_BITMAP_CARET_INSERT         156
#define IDC_EDIT_HILIMIT                157
#define IDC_EDIT_LOLIMIT                158
#define IDB_UNIT_LIBRARY                158
#define IDC_EDIT_COMMENT                159
#define IDB_UNIT_AND                    159
#define IDC_EDIT_K3                     160
#define IDB_UNIT_OR                     160
#define IDB_UNIT_XOR                    161
#define ID_INDICATOR_TIME               162
#define IDB_BITMAP_UNIT_DYNlINK         162
#define IDC_COMBO_CHOICE_OBJECT         163
#define IDB_UNIT_PULSE                  163
#define IDD_DEL_COMPONENT_PARAMETER     163
#define IDC_EDIT_DELAY_ON               164
#define IDB_UNIT_DELAY                  164
#define IDD_CHOICE_CUCP_LINK            164
#define IDC_ENABLE_ALARM                165
#define IDB_UNIT_ROTATE                 165
#define IDD_UNIT_COMPONENT              165
#define IDD_DIALOG_UNIT_COMPONENT       165
#define IDC_ALARM_HIGH                  166
#define IDB_UNIT_ADD                    166
#define IDB_UNIT_MULTIPLE               167
#define IDB_UNIT_DIVIDE                 168
#define IDB_UNIT_SINE                   169
#define IDB_UNIT_INVERT                 170
#define IDB_UNIT_DTIME                  171
#define IDB_UNIT_FFLP                   172
#define IDB_UNIT_HPBG                   173
#define IDB_UNIT_HSEL                   174
#define IDC_EDIT_DELAY_OFF              175
#define IDB_UNIT_IPOP                   175
#define IDC_HighPass                    176
#define IDB_UNIT_LSEL                   176
#define IDC_EDIT_BARGIN                 177
#define IDB_UNIT_MSEL                   177
#define IDC_EDIT_WIDTH                  178
#define IDB_UNIT_PID                    178
#define IDB_UNIT_SWCH                   179
#define IDC_NUMBER_OF_INPUT             180
#define IDC_NUMBER_OF_STEP              181
#define IDC_INIT_COIL                   182
#define IDC_INIT_OUTPUT                 183
#define IDC_STEP1_INPUT_PATTERN         184
#define IDC_STEP2_INPUT_PATTERN         185
#define IDC_STEP1_COIL_PATTERN          186
#define IDC_STEP2_COIL_PATTERN          187
#define IDC_STEP3_COIL_PATTERN          188
#define IDC_STEP4_COIL_PATTERN          189
#define IDC_STEP5_COIL_PATTERN          190
#define IDC_STEP6_COIL_PATTERN          191
#define IDC_STEP7_COIL_PATTERN          192
#define IDC_STEP8_COIL_PATTERN          193
#define IDC_STEP3_INPUT_PATTERN         194
#define IDC_STEP4_INPUT_PATTERN         195
#define IDC_STEP5_INPUT_PATTERN         196
#define IDC_STEP6_INPUT_PATTERN         197
#define IDC_STEP7_INPUT_PATTERN         198
#define IDC_STEP8_INPUT_PATTERN         199
#define IDC_STEP1_COIL_OUTPUT           200
#define IDC_STEP2_COIL_OUTPUT           201
#define IDC_STEP3_COIL_OUTPUT           202
#define IDC_STEP4_COIL_OUTPUT           203
#define IDC_STEP5_COIL_OUTPUT           204
#define IDC_STEP6_COIL_OUTPUT           205
#define IDC_STEP7_COIL_OUTPUT           206
#define IDC_STEP8_COIL_OUTPUT           207
#define IDC_STEP1_DIGITAL_OUTPUT        208
#define IDC_STEP2_DIGITAL_OUTPUT        209
#define IDC_STEP3_DIGITAL_OUTPUT        210
#define IDC_STEP4_DIGITAL_OUTPUT        211
#define IDC_STEP5_DIGITAL_OUTPUT        212
#define IDC_STEP6_DIGITAL_OUTPUT        213
#define IDC_STEP7_DIGITAL_OUTPUT        214
#define IDC_STEP8_DIGITAL_OUTPUT        215
#define IDC_STEP1_MC                    216
#define IDC_STEP2_MC                    217
#define IDC_STEP3_MC                    218
#define IDC_STEP4_MC                    219
#define IDC_STEP5_MC                    220
#define IDC_STEP6_MC                    221
#define IDC_STEP7_MC                    222
#define IDC_STEP8_MC                    223
#define IDC_AUTO                        229
#define IDC_FiltFactor                  231
#define IDC_DeadBand                    232
#define IDC_UNIT_TO_OBJECT              234
#define IDC_OBJECT_TO_UNIT              235
#define IDC_LIST_DYNLINK                236
#define IDC_UNIT_NAME                   239
#define IDC_CHECK_RECORD                241
#define IDC_COMBO_TYPE                  243
#define IDC_EDIT_PB                     246
#define IDC_EDIT_INTG                   247
#define IDC_EDIT_DERV                   248
#define IDC_EDIT_GAIN                   249
#define IDC_EDIT_NUMBER                 250
#define IDC_EDIT_DELAY_TIME             251
#define IDC_EDIT_PERIOD_TIME            252
#define IDC_CHECK_VERTICAL              255
#define IDC_CHECK_SHOWRANGE             256
#define IDC_EDIT_ROUND_LENGTH           258
#define IDC_STATIC_UNIT_TO_OBJECT       262
#define IDC_COMBO1                      263
#define IDC_ORDER0                      263
#define IDC_COMBO_INPUT_TYPE            263
#define IDC_COMBO2                      264
#define IDC_OBJECT0                     264
#define IDC_COMBO3                      265
#define IDC_EDIT1                       266
#define IDC_PARA0                       266
#define IDC_SYSTEM_DEBUG_PERIOD         266
#define IDC_STATIC1                     267
#define IDC_STATIC2                     268
#define IDC_STATIC3                     269
#define IDC_STATIC4                     270
#define IDC_STATIC5                     271
#define IDC_STATIC6                     272
#define IDC_STATIC7                     273
#define IDC_STATIC8                     274
#define IDC_STATIC9                     275
#define IDC_STATIC10                    276
#define IDC_STATIC11                    277
#define IDC_STATIC12                    278
#define IDC_NEXT_BUTTON                 279
#define IDC_PREV_BUTTON                 280
#define IDC_PHYSICAL_MEM                281
#define IDC_DISK_SPACE                  282
#define IDC_CHECK_TRANSPARENT           285
#define IDC_BUTTON_CHOOSE_FONT          286
#define IDC_LIST_COMPONENT_DEL          288
#define IDC_COMBO_CHOICE_CUCPARAMETER   289
#define IDC_LIST_UNITCOMPONENT          292
#define IDC_COMBO4                      323
#define IDC_ORDER1                      323
#define IDC_COMBO5                      324
#define IDC_OBJECT2                     324
#define IDC_COMBO6                      325
#define IDC_EDIT2                       326
#define IDC_PARA1                       326
#define IDC_COMBO7                      327
#define IDC_ORDER2                      327
#define IDC_COMBO8                      328
#define IDC_OBJECT1                     328
#define IDC_COMBO9                      329
#define IDC_EDIT3                       330
#define IDC_PARA2                       330
#define IDC_COMBO10                     331
#define IDC_OBJECT3                     331
#define IDC_COMBO11                     332
#define IDC_COMBO12                     333
#define IDC_ORDER3                      333
#define IDC_EDIT4                       334
#define IDC_PARA3                       334
#define IDC_COMBO13                     335
#define IDC_OBJECT9                     335
#define IDC_COMBO15                     337
#define IDC_ORDER4                      337
#define IDC_EDIT5                       338
#define ID_PARA9                        338
#define IDC_COMBO16                     339
#define IDC_OBJECT5                     339
#define IDC_COMBO17                     340
#define IDC_COMBO18                     341
#define IDC_ORDER5                      341
#define IDC_EDIT6                       342
#define IDC_PARA5                       342
#define IDC_COMBO19                     343
#define IDC_OBJECT6                     343
#define IDC_COMBO20                     344
#define IDC_COMBO21                     345
#define IDC_ORDER6                      345
#define IDC_EDIT7                       346
#define IDC_PARA6                       346
#define IDC_COMBO22                     347
#define IDC_OBJECT7                     347
#define IDC_COMBO23                     348
#define IDC_COMBO24                     349
#define IDC_ORDER7                      349
#define IDC_EDIT8                       350
#define IDC_PARA7                       350
#define IDC_COMBO25                     351
#define IDC_OBJECT8                     351
#define IDC_COMBO26                     352
#define IDC_COMBO27                     353
#define IDC_ORDER8                      353
#define IDC_EDIT9                       354
#define IDC_PARA8                       354
#define IDC_COMBO28                     355
#define IDC_OBJECT4                     355
#define IDC_COMBO30                     357
#define IDC_EDIT10                      358
#define IDC_PARA4                       358
#define IDC_COMBO32                     360
#define IDC_COMBO33                     361
#define IDC_COMBO34                     363
#define IDC_COMBO35                     364
#define IDC_COMBO36                     365
#define IDC_EDIT12                      366
#define IDC_COMBO37                     367
#define IDC_COMBO38                     368
#define IDC_COMBO39                     369
#define IDC_ORDER9                      369
#define IDC_EDIT13                      370
#define ID_ERROR_STRATEGY_TOO_MANY_START_POINT 1000
#define ID_ERROR_STRATEGY_TOO_MANY_START_POIN 1000
#define ID_ERROR_STRATEGY_LOOP_DETECT   1001
#define ID_ERROR_STRATEGY_COMPONENT_PARA_OVERFLOW 1010
#define ID_ERROR_FILE_VERSION           2000
#define ID_ERROR_LOAD_STRATEGY_FILE     2001
#define ID_ERROR_DACVIEW_LOAD_CSG_FILE  2003
#define ID_ERROR_SHOWVIEW_REALTIME_PROCESS_ERROR 3001
#define ID_ERROR_SHOWVIEW_REALTIME_PROCESS_OVERFLOW 3002
#define ID_ERROR_CANCEL_SHOWVIEW_FILE   3002
#define ID_ERROR_SHOWVIEW_REALTIME_PROCESS_CANNOT_CREATE 3003
#define ID_ERROR_SHOWVIEW_CANNOT_CREATE_VIEW 3004
#define ID_ERROR_SHOWVIEW_STRATEGY_FILE 3010
#define ID_ERROR_SHOWVIEW_DACVIEW_FILE  3011
#define ID_ERROR_OUT_OF_MEMORY          4001
#define ID_ERROR_CANNOT_FIND_FILE       4002
#define ID_ERROR_READ_OBJECT            4003
#define ID_ERROR_READ_FILE              4004
#define ID_ERROR_FIND_FILE              4005
#define ID_ERROR_OPEN_FILE              4006
#define ID_ERROR_SET_TIMER              4007
#define ID_ERROR_REALTIME_PROCESS       4008
#define ID_ERROR_KILL_TIMER             4009
#define ID_ERROR_CLOSE_SYSTEM           4010
#define ID_ERROR_DYNAMIC_LINK_TYPE_MISMATCH 4012
#define ID_WARN_INPUT_VALUE_OUT_OF_RANGE 5000
#define ID_WARN_REALTIME_SYSTEM_OVERFLOW 5100
#define ID_WARN_SYSTEM_OVERFLOW         5101
#define ID_WARN_LINK_METHOD_MISMATCH    6001
#define ID_ERROR_DACVIEW_CANNOT_MAKE_SYMBOL 6002
#define IDS_WARN_LOAD_OBJECT_VERSION    6010
#define ID_MSG_SUCCESS_COMPILE          8000
#define ID_MSG_FAIL_COMPILE             8001
#define ID_MESSAGE_UNIT_STATUS_VIEW     8010
#define IDC_LIST_MESSAGE                32001
#define ID_ARRANGE_TOFRONT              32768
#define ID_ARRANGE_TOBACK               32769
#define ID_EDIT_DELETE                  32770
#define ID_ARRANGE_MAKESYMBOL           32771
#define ID_ARRANGE_BREAKSYMBOL          32772
#define ID_PROJECT_NEW                  32773
#define ID_PROJECT_OPEN                 32774
#define ID_PROJECT_CLOSE                32775
#define ID_PROJECT_EDIT                 32776
#define ID_ARRANGE_DYNAMICLINK          32777
#define ID_PROJECT_DICTIONARY           32778
#define ID_PROJECT_COMPILE              32779
#define ID_BLOCK_INPUTOUTPUT_AIN        32781
#define ID_BLOCK_INPUTOUTPUT_AOUT       32782
#define ID_FUNCTION_INPUTOUTPUT_DIN     32783
#define ID_FUNCTION_INPUTOUTPUT_DOUT    32784
#define ID_FUNCTION_INPUTOUTPUT_TPO     32785
#define ID_FUNCTION_INPUTOUTPUT_AINS    32786
#define ID_BLOCK_INPUTOUTPUT_AOTS       32787
#define ID_FUNCTION_INPUTOUTPUT_DINS    32788
#define ID_FUNCTION_INPUTOUTPUT_DOTS    32789
#define ID_BLOCK_INPUTOUTPUT_AKBD       32790
#define ID_BLOCK_INPUTOUTPUT_DKBD       32791
#define ID_FUNCTION_INPUTOUTPUT_HORN    32792
#define ID_FUNCTION_ARITHMATIC_DTIM     32793
#define ID_FUNCTION_ARITHMATIC_ALRM     32794
#define ID_FUNCTION_ARITHMATIC_COND     32795
#define ID_BLOCK_INPUTOUTPUT_DIN        32796
#define ID_BLOCK_INPUTOUTPUT_DOUT       32797
#define ID_BLOCK_INPUTOUTPUT_TPO        32798
#define ID_BLOCK_INPUTOUTPUT_AINS       32799
#define ID_BLOCK_INPUTOUTPUT_DINS       32800
#define ID_BLOCK_INPUTOUTPUT_DOTS       32801
#define ID_BLOCK_INPUTOUTPUT_HORN       32802
#define ID_TOGGLE_INSERT                32803
#define ID_BLOCK_ARITHMATIC_DTIM        32803
#define ID_BLOCK_ARITHMATIC_ALRM        32804
#define ID_BLOCK_ARITHMATIC_COND        32805
#define ID_BLOCK_ARITHMATIC_HFLT        32806
#define ID_BLOCK_MATHMATIC_ADD          32808
#define ID_FILE_LOADSTRATEGYFILE        32809
#define ID_BLOCK_SIMULATE_QUADRATIC     32811
#define ID_BLOCK_SIMULATE_LOGARITHM     32812
#define ID_BLOCK_SIMULATE_SININE        32813
#define ID_BLOCK_SIMULATE_SINE          32814
#define ID_VIEW_VIEWIN                  32815
#define ID_VIEW_VIEWOUT                 32816
#define ID_ARRANGE_MAKECOMPOUND         32817
#define ID_ARRANGE_BREAKCOMPOUND        32818
#define ID_BLOCK_COMPOUND               32819
#define ID_OBJECT_SELECT                32822
#define ID_OBJECT_ERASE                 32823
#define ID_OBJECT_PEN                   32824
#define ID_OBJECT_BRUSH                 32825
#define ID_OBJECT_PAINT                 32826
#define ID_OBJECT_LIBRARY               32827
#define ID_OBJECT_DYNAMICLINK           32828
#define ID_OBJECT_TEXT                  32829
#define ID_OBJECT_RECT                  32830
#define ID_OBJECT_ROUNDRECT             32831
#define ID_OBJECT_OVAL                  32832
#define ID_OBJECT_LINE                  32833
#define ID_BLOCK_MATHMATIC_MULTIPLE     32838
#define ID_OBJECT_GRAPH                 32839
#define ID_OBJECT_COMPOUND              32840
#define ID_BLOCK_BASICLOGIC_AND         32841
#define ID_BLOCK_BASICLOGIC_OR          32842
#define ID_BLOCK_BASICLOGIC_XOR         32843
#define ID_BLOCK_BASICLOGIC_INV         32845
#define ID_BLOCK_BASICLOGIC_DROT        32847
#define ID_BLOCK_ADVANCELOGIC_FFLP      32848
#define ID_BLOCK_ADVANCELOGIC_ICNT      32849
#define ID_BLOCK_ADVANCELOGIC_TTB       32850
#define ID_BLOCK_ADVANCELOGIC_TTBE      32851
#define ID_BLOCK_BASICLOGIC_PULS        32852
#define ID_BLOCK_BASICLOGIC_DLAY        32853
#define ID_BLOCK_BASICCONTROL_PID       32854
#define ID_BLOCK_BASICCONTROL_INTD      32855
#define ID_BLOCK_BASICCONTROL_PD        32856
#define ID_BLOCK_BASICCONTROL_AMB       32857
#define ID_BLOCK_BASICCONTROL_TIME      32858
#define ID_BLOCK_ADVANCECONTROL_SEQ     32859
#define ID_BLOCK_ADVANCECONTROL_SEQE    32860
#define ID_BLOCK_ADVANCECONTROL_SCHD    32861
#define ID_BLOCK_HISTORYTREND_AHST      32863
#define ID_BLOCK_HISTORYTREND_DHST      32864
#define ID_BLOCK_HISTORYTREND_RPRT      32865
#define ID_BLOCK_HISTORYTREND_SPC       32866
#define ID_BLOCK_MATHMATIC_DIV          32867
#define ID_BLOCK_MATHMATIC_AVG          32868
#define ID_BLOCK_MATHMATIC_AVGT         32869
#define ID_BLOCK_MATHMATIC_EXPR         32870
#define ID_BLOCK_ARITHMATIC_LLAG        32871
#define ID_BLOCK_ARITHMATIC_TOT         32872
#define ID_BLOCK_ARITHMATIC_CHAR        32873
#define ID_BLOCK_ARITHMATIC_QFLT        32874
#define ID_BLOCK_SELECT_SWCH            32875
#define ID_BLOCK_SELECT_HSEL            32876
#define ID_BLOCK_SELECT_LSEL            32877
#define ID_BLOCK_SELECT_MSEL            32878
#define ID_BLOCK_ARITHMATIC_HPBG        32881
#define ID_OBJECT_PUSHBUTTON            32882
#define ID_OBJECT_SLIDER                32883
#define ID_ARRANGE_MAKEDYNLINK          32884
#define ID_ARRANGE_BREAKDYNLINK         32885
#define ID_OBJECT_GAUGE                 32886
#define ID_BLOCK_INPUTOUTPUT_SIM        32887
#define ID_OBJECT_KNOB                  32891
#define ID_RUN_RUN                      32893
#define ID_RUN_STOP                     32894
#define ID_RUN_PAUSE                    32895
#define ID_OBJECT_METER                 32896
#define ID_OBJECT_FILLBAR               32897
#define ID_VIEW_PROPERTY                32899
#define ID_FILE_TASKLIST                32903
#define ID_FILE_VIEWTASKLIST            32904
#define ID_TASKLIST_CREATE              32905
#define ID_FILE_SELECTTASKLIST          32906
#define ID_TASKLIST_VIEW                32907
#define ID_TASKLIST_SELECT              32908
#define ID_TASKLIST_DELETE              32910
#define ID_TASKLIST_NEXT                32911
#define ID_TASKLIST_PREV                32912
#define ID_RUN_RESUME                   32913
#define ID_OBJECT_NUMBERINPUT           32914
#define ID_ARRANGE_TOGGLECUTOFF         32915
#define ID_VIEW_PREV                    32920
#define ID_VIEW_NEXT                    32921
#define ID_VIEW_UNITLIBRARY             32922
#define ID_VIEW_MESSAGEBAR              32925
#define ID_OBJECT_PICTURE               32926
#define ID_VIEW_STATUS                  32927
#define ID_ARRANGE_COMPONENT            32928
#define ID_BLOCK_COMPONENT              32929
#define ID_ARRANGE_LINK_INTO_COMPONENT  32931
#define ID_BREAK_LINK_OF_COMPONENT      32932
#define ID_VIEW_OBJECTBAR               32933
#define ID_Menu                         32934
#define ID_ARRANGE_COMPILE_COMPONENT    32936
#define ID_ARRANGE_RELEASE_ENCAPSULATION 32938
#define ID_ARRANGE_DECAPSULATION        32940
#define ID_ARRANGE_ENCAPSULATION        32941
#define ID_ARRANGE_LinkFromComponent    32943
#define ID_OPTION_SYSTEM                32944
#define ID_STYLE_LEFT                   33000
#define ID_STYLE_CENTERED               33001
#define ID_STYLE_RIGHT                  33002
#define ID_STYLE_JUSTIFIED              33003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32945
#define _APS_NEXT_CONTROL_VALUE         294
#define _APS_NEXT_SYMED_VALUE           163
#endif
#endif
